# --------------------------------------------------
# Site settings

title: Beyond analytics
description: dbt learn is a two-day in-person training program designed to empower analysts.
owner: http://github.com/fishtown-analytics
repo: learn.getdbt.com
branch: master
robots: true

# --------------------------------------------------
# Site imagery

favicon: favicon.ico
avatar: learn.getdbt.com/ui/img/graph/avatar.png
poster: learn.getdbt.com/ui/img/graph/poster.png

# --------------------------------------------------
# the subpath of your site, e.g. /blog

url: "http://learn.getdbt.com"
baseurl: "/"
stylesurl: "www.getdbt.com"

# css container
namespace: dbt

# --------------------------------------------------
# Build settings

includes_dir: _config/_includes
layouts_dir: _config/_layouts

sass:
  style: compressed
  sass_dir: www.getdbt.com/ui/_sass

collections:
  content:
    output: true
    permalink: /:path/
  lessons:
    output: true
    permalink: /:collection/:path

defaults:
-
  scope:
    path: ""
    type: "styles"
  values:
    layout: "style-spec"
-
  scope:
    path: ""
    type: "content"
  values:
    layout: "page"
