name: Sources
slug: sources
live: false

learningObjectives:
  - Explain the purpose of sources in dbt
  - Configure and select from sources in your data warehouse
  - Configure tests and write documentation for sources

presentationName: Sources
presentationSlug: sources
  
pages: 
  - name: What are sources?
    slug: sources-what
    assetName: What are sources?
    assetLink: 
    assetType: video
  
  - name: Learning Objectives
    slug: learning-objectives
    assetName: false
    assetLink:
    assetType:
      
  - name: Configure and select from sources
    slug: sources-define
    assetName:
    assetLink:
    assetType:
    
  - name: Testing and Documenting Sources
    slug: sources-tests-docs
    assetName:
    assetLink:
    assetType:
